### ISSUE TITLE
Missing end times in kulke importer

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents#101]
http://linkedevents.hel.fi/#/event/kulke%3A36628/?_k=wusnna

**Comment by juyrjola** [comment]
I'm not sure if there's anything we can do about that on our end... The data is missing from source:

```
    <eventstarttime>Sat, 09 Apr 2016 14:00:00 GMT</eventstarttime>
    <eventendtime/>
```

**Comment by aleksisalonen** [comment]
Edmon Dolaian from kulke informed me that the end time is switched off in their end. They're going to solve it internally.
