### ISSUE TITLE
Add license support for images

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/linkedevents#117]
Support two license types to start with:

- CC 4.0 BY
- "Event only"

**Comment by Rikuoja** [comment]
FI

"Helsingin kaupungilla on kuviin kaikki oikeudet. Mikäli rajapinnassa jaettavan kuvan tietojen kohdassa [tähän määritellään tietty kenttä rajapinnassa] on merkintä ”event_only”, saa kuvaa käyttää ainoastaan kuvan tapahtumaa käsittelevään tiedotukseen ja viestintään. Kuvien käyttäminen tähän tarkoitukseen on käyttäjälle ilmaista. Kuvan käyttö tai siirto muihin tarkoituksiin on kielletty. Kuvia käytettäessä on ehdottomasti mainittava kuvien lähde ja kuvaaja."

**Comment by Rikuoja** [comment]
SVE:

”Helsingfors stad äger alla rättigheter till bilderna. Om beteckningen ”event only” förekommer under [NNN] i uppgifterna för en bild som delas i gränssnittet, får bilden användas endast för informering eller kommunikation som gäller evenemanget på bilden. Att använda bilderna för det här ändamålet är gratis. Att använda eller flytta bilden för andra ändamål är förbjudet. Vid användning av bilder ska källan och fotografen absolut nämnas.”

EN:

”The City of Helsinki reserves all rights to the images. If the data at [NNN] of an image shared in the interface contains the text “event only”, then the image can only be used for information and communications connected to the event depicted in the image. The images can be used free of charge for this purpose. To use or move the image for other purposes is forbidden. The source and photographer must absolutely be mentioned when using an image.”

**Comment by juyrjola** [comment]
License attributes:

- id: event_only, cc_by
- name (translatable)
- url
