### ISSUE TITLE
Reorganize "kohderyhmät" on yso basis, add sote categories

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents#118]

**Comment by Rikuoja** [comment]
Add "Palvelukeskuskortin haltijat" as Keyword.

**Comment by Rikuoja** [comment]
Map existing hel.fi Keywords to YSO, verify with Aleksi before discarding hel.fi Keywords.

**Comment by Rikuoja** [comment]
Add KeywordSet "Kohderyhmät" containing SOTE and Hel.fi target groups.

**Comment by aleksisalonen** [comment]
New sote keywords to add: 

* Omaishoitoperheet
* Palvelukeskuskortti

Already in yso: 
* Mielenterveyskuntoutujat
* Päihdekuntoutujat
