### ISSUE TITLE
Forbidden dump file

### ISSUE THREAD

**Issue by anttileppa** [City-of-Helsinki/linkedevents#171]
When trying to download the dump file from http://api.hel.fi/linkedevents/static/linkedevents.dump.gz i receive 403 - Forbidden instead file.

Steps to reproduce problem:

    wget -O - http://api.hel.fi/linkedevents/static/linkedevents.dump.gz

Response:

    --2016-12-26 11:47:10--  http://api.hel.fi/linkedevents/static/linkedevents.dump.gz
    Resolving api.hel.fi (api.hel.fi)... 185.20.137.45
    Connecting to api.hel.fi (api.hel.fi)|185.20.137.45|:80... connected.
    HTTP request sent, awaiting response... 403 Forbidden
    2016-12-26 11:47:10 ERROR 403: Forbidden.

**Comment by hugovk** [comment]
wgetting it now says:
```
Hello there!

We're deeply sorry, but we had to remove the database dump from public view.
Currently we recommend using the official API you need to use Helsinki event
information. If you have some need for the whole database contact us at:
dev@hel.fi

(The api is at https://api.hel.fi/linkedevents/v1)
```
