### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by hugovk** [City-of-Helsinki/linkedevents#174]
1. Go to https://dev.hel.fi/apis/linked-events/
2. Click the "[City of Helsinki Cultural Office](http://www.hel.fi/hki/Kulke/)" link

Actual: Page not found

Expected: Page is found. Perhaps use http://www.hel.fi/www/kulke/en?

(Is the source for https://dev.hel.fi/apis/linked-events/ somewhere here on GitHub? If so I could PR if I find any more.)

**Comment by Rikuoja** [comment]
@hugovk Thanks, link fixed!

https://github.com/City-of-Helsinki/devheldev is the repository for https://dev.hel.fi , but as it's a Wagtail CMS, the problem was in the content, not the code.
