### ISSUE TITLE
Provide preformatted docx event listings for places

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#209]
Users should be able to request a preformatted docx-format event listing for any event-endpoint location-search result. The feature is specifically to be used for making simple printouts to be handed out to people with low internet access/skills.

The docx-file should be available for download by adding an additional parameter to the event-endpoint request.

For example http://api.hel.fi/linkedevents/v1/event/?location=tprek:28473&format=docx

should output a docx-document containing all future events for City Hall in a format defined below.

The format=docx-parameter should also accept values that include an additional day-count. 

For example http://api.hel.fi/linkedevents/v1/event/?location=tprek:28473&format=docx-180 (or similar format) should output all events for City Hall between the current day and current+180d.

The human readable finnish name for the place should be show in output, eg.
http://api.hel.fi/linkedevents/v1/event/?location=tprek:28473&format=docx
should produce the heading "Tapahtumat: Helsingin kaupungintalo"

* Output should be ordered from nearest to furthest event.
* Events that have the same start date and end date and share that date, should be grouped under a shared date heading.
* Events that span multiple days should be shown on their own in the list, and sorted according to their start date. Those event objects should display no starting or ending times (hours) or day names.

**Format for docx output:**
`Legend: "name"=API object name, [stuff]=descriptor, <h1></h1>=html semantic structure`

***

```
<h1>Tapahtumat: ["location"->"name"]</h1>
<strong>[current date] dd.mm.yyyy–dd.mm.yyyy [current+n, if defined in parameter]</strong>

<h2>["start_time" date only, if concurrent with "end_time" date] dd.mm. [day name]</h2>
<h3>Klo [starting time] hh:mm–hh:mm [ending time] [Event "name"]</h3>
<p>["short_ description"] [If event has "offers"->"is_free": false, display: <strong>Hinta: "offers"->"price"</strong>]</p>
<h3>Klo [starting time] hh:mm–hh:mm [ending time] [Event "name"]</h3>
<p>["short_ description"] [If event has "offers"->"is_free": false, display: <strong>Hinta: "offers"->"price"</strong>]</p>

<h2>["start_time"] dd.mm.–dd.mm.["end_time"]</h2>
<h3>[Event "name"]</h3>
<p>["short_ description"] [If event has "offers"->"is_free": false, display: <strong>Hinta: "offers"->"price"</strong>]</p>

<h2>["start_time" date only, if concurrent with "end_time" date] dd.mm. [day name]</h2>
<h3>Klo [starting time]–[ending time]  [Event "name"]</h3>
...
```

**Example:**

```
<h1>Tapahtumat: Kampin palvelukeskus</h1>
<strong>15.02.2017–30.5.2017</strong>
<h2>15.02. Tiistai<h2>
<h3>klo 12:00–13:15 Keppijumppaa</h3>
<p>Auringon kiivetessä korkealle Kivikon tykkitiet ja kalliot lämpeävät houkutteleviksi käärmeille ja vaskitsoille.</p>
<h3>klo 14:00–15:00 Tuolivoimistelua </h3>
<p>Auringon kiivetessä korkealle Kivikon tykkitiet ja kalliot lämpeävät houkutteleviksi käärmeille ja vaskitsoille.</p>
<h2>15.02.–17.05.<h2>
<h3>Joogalentoa</h3>
<p>Auringon kiivetessä korkealle Kivikon tykkitiet ja kalliot lämpeävät houkutteleviksi käärmeille ja vaskitsoille. <strong>Hinta: 10e</strong></p>
...
```

**Comment by maxg0** [comment]
I am currently working on this. What would be a reasonable filename?

**Comment by aleksisalonen** [comment]
Let's say [place-name]-tapahtumat-[ddmm]-[ddmm].docx

eg. kampin-palvelukeskus-tapahtumat-1905-2507.docx
