### ISSUE TITLE
Invalid, relative URLs for images

### ISSUE THREAD

**Issue by hugovk** [City-of-Helsinki/linkedevents#230]
Some events have images with relative URLs, which essentially renders the record invalid, and it's causing us problems.

For example: https://api.hel.fi/linkedevents/v1/image/38028/ contains:
```json
 "url": "instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_603671.jpg",
```
Which can be found at http://www.espanlava.fi/instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_603671.jpg

Would it be possible to do the following?

1) Correct the data for those invalid listed below, and for any other invalid URLs
2) Add validation so invalid URLs don't appear in the API (eg. prevent existing invalid data showing up to API users, and prevent invalid data being entered in the first place)

---

So far I've identified these records with these invalid URLs:

https://api.hel.fi/linkedevents/v1/image/36508/
https://api.hel.fi/linkedevents/v1/image/36760/
https://api.hel.fi/linkedevents/v1/image/37233/
https://api.hel.fi/linkedevents/v1/image/37229/
https://api.hel.fi/linkedevents/v1/image/37435/
https://api.hel.fi/linkedevents/v1/image/37443/
https://api.hel.fi/linkedevents/v1/image/37587/
https://api.hel.fi/linkedevents/v1/image/37603/
https://api.hel.fi/linkedevents/v1/image/37655/
https://api.hel.fi/linkedevents/v1/image/38028/
https://api.hel.fi/linkedevents/v1/image/35686/
https://api.hel.fi/linkedevents/v1/image/36246/

'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_602406.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_601524.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_605340.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_605339.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_603032.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_602437.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_604034.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_602697.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_607032.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_603671.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_599911.jpg'
'instancedata/prime_product_resurssivaraus/kulke/embeds/EventPic_602992.jpg'

At least for these, they can be found on http://www.espanlava.fi/

**Comment by aleksisalonen** [comment]
This problem pertains to deficient kulke-data, which is received "as is" via importer. I'll contact them directly and ask for a fix. The relative url's all seem to be associated with the place Espan lava. If you come across others, let us know.

**Comment by hugovk** [comment]
Thank you. Do you think validation would improve the "as is" importer? I'll let you know if we find any more.
