### ISSUE TITLE
Make importer encode kulke description data in html

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#232]
Kulke data importer should be changed so that "description" data is encoded in html in Linked Events.

**Comment by Rikuoja** [comment]
Fixed in https://github.com/City-of-Helsinki/linkedevents/commit/f2728d9ff71b27b91ebb5ff6009c7da380f29e47

**Comment by Rikuoja** [comment]
This is fixed in master, it's just not in production yet so the importer hasn't been run.
