### ISSUE TITLE
Add filter for fetching subevents for a specific superevent

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents#247]
Needed for the UI. Add `?super_event=event_id` filter to the `/v1/event` endpoint that allows fetching all events belonging to a specific superevent.

**Comment by Rikuoja** [comment]
UI issue https://github.com/City-of-Helsinki/linkedevents-ui/issues/259

**Comment by mingfeng** [comment]
It seems this is done in: https://github.com/mingfeng/linkedevents/commit/f3fef74b62eb113df9b3d3560e1edcb9f35edd46

**Comment by Rikuoja** [comment]
Wow! I did it myself this summer and didn't even remember! 😂
