### ISSUE TITLE
Create data importer for Lippupiste

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#256]
A data importer from Lippupiste data dump to Linked Events event should be created.

Lippupiste data is formatted as a csv-file. A sample csv-file and Lippupiste data description brochure are attached as well a correlation table for Lippupiste and Linked Events fields.

Things of note:
1) Solving how place-information is imported from Lippupiste to Linked Events.
2) Solving how / if Superevents will be created from Lippupiste event series'.
3) At first only data for the City Theater will be imported. Address for the data dump will be provided later.
[Lippupiste_Tapahtumakalenteri_HKT.pdf](https://github.com/City-of-Helsinki/linkedevents/files/1767349/Lippupiste_Tapahtumakalenteri_HKT.pdf)
[Lippupiste-data-sample-HKT.txt](https://github.com/City-of-Helsinki/linkedevents/files/1767350/Lippupiste-data-sample-HKT.txt)
[LP-LE-muunto.xlsx](https://github.com/City-of-Helsinki/linkedevents/files/2072358/LP-LE-muunto.xlsx)

**Comment by aleksisalonen** [comment]
Data source and publisher ID for Lippupiste:

    "data_source": "lippupiste",
    "publisher": "ytj:0586977-6",

**Comment by Rikuoja** [comment]
The theaters found in City Theater data can be found in tprek, so it is easy to hard code these few locations so they are matched right.

However, in general (when the importer will be used for all Lippupiste locations), an inexact match based on the location name is needed, similar to the one existing in https://github.com/City-of-Helsinki/linkedevents/blob/master/events/importer/kulke.py#L236 .

However, here mismatches and non-matching locations (different names) will need to be checked and hard coded to tprek ids if present in tprek, or created as lippupiste locations if they cannot be found in tprek at all.

**Comment by aleksisalonen** [comment]
Done.
