### ISSUE TITLE
Add support for events in Chinese

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#259]
Add support for Chinese language event data in API.

**Comment by Rikuoja** [comment]
Done in https://github.com/City-of-Helsinki/linkedevents/commit/033510404ea418eeba9c350be42d3fc5bfbea6d1

**Comment by aleksisalonen** [comment]
Is it possible to get the checkboxes aligned in desktop and tablet modes, currently a little visually disorderly.

**Comment by Rikuoja** [comment]
Reopening so whoever has the time first can fix the box alignment :)

**Comment by Rikuoja** [comment]
Ah. Sorry. This is not the UI, not going to do that here.
