### ISSUE TITLE
Return events published by suborganizations and affiliated organizations with organization filter

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents#280]
Currently, the user only sees event published by the selected organization, when filtering the event endpoint with `?publisher` query.

Using the hierarchical MPTT tree, we should also return any events from any of the organizations below the specified organization in the tree.

**Comment by Rikuoja** [comment]
`?publisher_parent` parameter?

**Comment by Doatti** [comment]
> `?publisher_parent` parameter?

Maybe `?publisher_ancestor` would be a better name, since the publisher can be any ancestor, not only the direct parent?
