### ISSUE TITLE
Make events replaceable

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#294]
Events should have the propertie and related field:

1) is replaced by X

This will allow for a neat way of dealing with duplicates that exist in the API.

**Comment by Rikuoja** [comment]
The `replaced_by` field already exists for places `http://api.hel.fi/linkedevents/v1/place/`, and replaced locations give HTTP 301 to the new resource. Implement the same for events.

**Comment by aleksisalonen** [comment]
Duplicate of #341
