### ISSUE TITLE
Add super_event-type 'umbrella'

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#299]
Add a new type of super_event to API, called 'umbrella', for top level events (like festivals).

(Intended usage: Umbrella-events can have recurring-type super_events as their sub_events, but not the other way around. Umbrella-events should not have other umbrella events as their sub_events. Don't restrict on API side.)

**Comment by Rikuoja** [comment]
Currently, the API has no limitations on e.g. setting recurring events to have superevents and subevents that are recurring. I'm not sure if the API logic is the right place to prevent creating event hierarchies just because we don't want them at the moment.

**Comment by Rikuoja** [comment]
Mostly the problem would be that if this needs to be changed later (or multi-tiered data is imported), the logic will have to be rewritten, and we will limit other people wishing to use linkedevents for structured event data. It would make the software more general if it was less opinionated.

**Comment by aleksisalonen** [comment]
Sounds reasonable. It's most likely better that actual usage among different Linked Events instances is limited to similar patterns ("three-tiered limited"), but that can be accomplished without API restrictions.

**Comment by Rikuoja** [comment]
Yeah, our UI will prevent more complex hierarchies anyway. Probably this won't be an issue, unless in the future some third parties start spamming our API with very complex hierarchies in their own events.

**Comment by aleksisalonen** [comment]
Done.
