### ISSUE TITLE
Automatic email messages for certain event publishing events

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents#333]
To work in conjunction with issue https://github.com/City-of-Helsinki/linkedevents-ui/issues/242

The UI should be able to initiate the sending of automatic email messages based on the actions of a moderator and the actions of regular users posting drafts.

There are three types of messages to be sent:

1. If a moderator deletes an unpublished event, an automatic email (containing message 1) should be sent to the email address of the submitter.
2. If a moderator publishes an unpublished event, an automatic email (containing message 2) should be sent to the email address of the submitter.
3. If a draft is posted by a regular user, an automatic email (containing message 3) should be sent to the email address(es) of the admin users of the organization in question.
4. The messages should be sent for individual events that don't have a superevent and superevents, but not for subevents that have a superevent.

The solution should be done using the sendgrid/Mailgun-API, ask tech lead / Ville K. for more details.

**Comment by Rikuoja** [comment]
This happens most easily with anymail:

https://github.com/City-of-Helsinki/respa/blob/develop/respa/settings.py#L350

**Comment by Rikuoja** [comment]
This means we can copy the implementation from e.g. Respa, but the logic (probably signals?) will have to be custom-written.

**Comment by Rikuoja** [comment]
Ah, we may also use sendgrid instead: https://anymail.readthedocs.io/en/stable/esps/sendgrid/#sendgrid

**Comment by Rikuoja** [comment]
@vikoivun knows how to use them.

**Comment by Doatti** [comment]
How should we check if an event is "unpublished"? Is it `event.publication_status == PublicationStatus.DRAFT`? Also, do we need to check if the user who deleted/published the event is a moderator, or is this always the case?

**Comment by Rikuoja** [comment]
1) Yes, unpublished event means `event.publication_status == PublicationStatus.DRAFT`. Then publication just means that the status is changed from `DRAFT` to `PUBLISHED`.

2) No need to check. Only moderators are allowed to publish events. When deleting, it is possible that also draft creators themselves might be allowed to delete their drafts. In my opinion, it is no problem that a deletion email is triggered even if a person deletes their draft themself.
