### ISSUE TITLE
Add `has_regular_users` boolean field to Organization endpoint

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents#345]
Use case:

https://github.com/City-of-Helsinki/linkedevents-ui/issues/242 requires to be shown *only* when an admin organization has regular users (with drafting permissions). Therefore, just expose a public `has_regular_users` field` in `/v1/organizations`.

**Comment by Rikuoja** [comment]
Actually, the organization is serialized by the django app https://github.com/City-of-Helsinki/django-orghierarchy/blob/master/django_orghierarchy/api.py

**Comment by Rikuoja** [comment]
So we will need a new version of that, I'm afraid.

**Comment by Doatti** [comment]
I don't think we need to touch django-orghierarchy, because LinkedEvents has it's own OrganizationSerializer: https://github.com/City-of-Helsinki/linkedevents/blob/master/events/api.py#L984
