### ISSUE TITLE
Add structure for video

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#349]
Add a new information structure for video. Model after images, with a few substractions and the addition of alt-text. (Alt-text should be added to images too, in separate issue).

This is a **suggested** structure.

"videos": [
                    "created_time": "[time]",
                    "name": "[name]",
                    "alt": "[alt text]",
                    "url": "[external url]",
                    "@id": "[external url]",
                    "@context": "http://schema.org",
                    "@type": "VideoObject"
]

**Comment by Rikuoja** [comment]
Here we will need `id`: `internal id` and "@id": "[internal url]", as with images.

Also, this issue includes actually supporting inline creation of videos at event POST/PUT.

We don't want to support POST/PUT at the `/v1/video` endpoint, as the user will never need to create videos separate from an event.

Instead, an event should have `videos` array, and the backend should create/update video data inlined there at event POST/PUT.

**Comment by Rikuoja** [comment]
@aleksisalonen surely there is also a need for `publisher` and `license` fields?

**Comment by Rikuoja** [comment]
And for completeness' sake, `data_source` should be present just as in other LE objects. That way we differentiate e.g. imported video data from data created through the API.

**Comment by aleksisalonen** [comment]
Sure, let's add data source.

But, as ee are just providing a link, I think license and publisher data should be seen as issues handled at the video hosting service side.

**Comment by Rikuoja** [comment]
Hm okay. However, publisher is a Linkedevents internal organization (just like data source), so it would make sense to mark the publisher as the organization adding the data to Linkedevents.

**Comment by Rikuoja** [comment]
So I assume the video link then takes the user to a whole web service that displays the UI and the license etc., not just the raw video file.

**Comment by aleksisalonen** [comment]
It's basically going to be a Youtube, Vimeo (or Helsinki-kanava) link. Those services are built so that the same url can function both as basis for embedded content or a simple link to a web page.

**Comment by aleksisalonen** [comment]
Ok, let's add publisher too.

**Comment by Doatti** [comment]
@aleksisalonen should we add "last_modified_time" as well?

**Comment by aleksisalonen** [comment]
Ok, let's add that for comlpeteness and consistency.
