### ISSUE TITLE
Add keyword AND filter, !=keyword filter

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents#383]
Currently, comma-separated keywords extend the queryset, instead of narrowing it down further. Therefore, let's implement a `keyword_AND=` filter that requires ALL of the keywords to be present.

Also, let's add `keyword!=` filter, which lists all the keywords that should NOT be present. This should be combinable with the `keyword_AND=` filter.

For completeness' sake, let's also add `keyword_OR=`, which should do the same as the current `keyword=` filter. Then, the user can do some rudimentary combination of `keyword_AND=` and `keyword_OR=`, should be more than enough for now.

**Comment by Doatti** [comment]
What shuold happen, if both `keyword=` and `keyword_OR=` query parameters are present?

**Comment by Rikuoja** [comment]
Hm, i would expect they should not interfere if they have identical parameters? Let's do the same way as with other parameters, i.e. if both exist, we filter according to both.

**Comment by Doatti** [comment]
So we'll combine the two keyword lists? E.g. `keyword=1&keyword_OR=2` is the same as `keyword=1,2`?

**Comment by Rikuoja** [comment]
Yes, I would say that makes sense, so it works the same way as combining other filters.

**Comment by Doatti** [comment]
Well, it's not exactly the same as combining other filters, since other filters are effectively combined with a logical "and" between them.

**Comment by Doatti** [comment]
Or, did you mean what happens if the same query parameter is present multiple times? E.g. `data_source=1&data_source=2`?

Then I guess it's the same way :)

**Comment by Rikuoja** [comment]
Ah! My mistake. I'm afraid that to keep in line with other filters, we indeed have to do it with logical AND, so keyword=1&keyword_OR=2 wouldn't yield any events :D That should put off people trying to combine them.

Is that indeed what happens if the same query parameter is present? I thought one overrides the other if they are identical?

**Comment by Rikuoja** [comment]
I thought `params.get('data_source')` only gets one or the other. Does it return both?

**Comment by Doatti** [comment]
> I thought `params.get('data_source')` only gets one or the other. Does it return both?

Ah yes, you are correct. It seems that it only return the latter one. I think the specification is unclear how to handle duplicate keys, so the behavior depends on the framework used.

**Comment by Doatti** [comment]
> Ah! My mistake. I'm afraid that to keep in line with other filters, we indeed have to do it with logical AND, so keyword=1&keyword_OR=2 wouldn't yield any events :D That should put off people trying to combine them.

If we do it like that, `keyword=1&keyword_OR=2` would actually return events where both keywords 1 and 2 are present. So it would be equivalent to `keyword_AND=1,2`.

**Comment by Rikuoja** [comment]
> > Ah! My mistake. I'm afraid that to keep in line with other filters, we indeed have to do it with logical AND, so keyword=1&keyword_OR=2 wouldn't yield any events :D That should put off people trying to combine them.
> 
> If we do it like that, `keyword=1&keyword_OR=2` would actually return events where both keywords 1 and 2 are present. So it would be equivalent to `keyword_AND=1,2`.

Oh yes indeed, my mistake again :D I think that is a reasonable behaviour, as it is in line with combining other filters.
