### ISSUE TITLE
Stop Lippupiste importer from updating past events

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#384]
The importer is importing data for past events daily. This is unnecessary. 

Change the importer so that it does not import past data.

**Comment by Doatti** [comment]
In my testing, I found that the Lippupiste API already filters out events whose date is earlier than the current date. So the only past events returned are from today at a time less than current time. At the time of testing, only 3 events out of ~8400 were in the past.

Does this sound right?

**Comment by aleksisalonen** [comment]
Checking from the UI side, it does seem like a bunch of old events are still being updated. This is a screencap just now:

![today-screencap-lippupiste](https://user-images.githubusercontent.com/16101544/75030241-5e371e00-54ac-11ea-8fc8-9b412b84c1fe.jpg)

It looks like just the top-level serie-events are being updated, not the subevents under them. 

![today-screencap-lippupiste-](https://user-images.githubusercontent.com/16101544/75030484-e4536480-54ac-11ea-83a4-95b1234bb08a.jpg)

**Comment by aleksisalonen** [comment]
That might point to the direction of some facet of the importer itself being behind this mischief.

**Comment by Doatti** [comment]
Okay, I think I know what's going on. At the end of the importer script, ALL super-events' names and start/end times are updated, even if no changes were made to the sub-events. So, the "last modified" time is updated unnecessarily. I think we should only update those super-events whose sub-events were updated.

**Comment by aleksisalonen** [comment]
Sounds good.
