### ISSUE TITLE
Allow listing also deleted events (places, keywords) with the parameter `?show_deleted=True`

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents#385]
This way, a client could see if a resource (e.g. event) has been deleted since they last checked the API. This helps huge clients with local copies of data, such as IBM and MyHelsinki.

Combined with the `?last_modified_since=` filter, this would help such clients update *all* data that has been modified after their last visit, including recently deleted items, instead of having to go through the whole dataset.

**Comment by Rikuoja** [comment]
To prevent actually using the data, we could even display a completely empty event, with only the `deleted=True` flag and the event id displayed in the json.

**Comment by Doatti** [comment]
`show_deleted` and `show_deprecated` have already been implemented for places and keywords: https://github.com/City-of-Helsinki/linkedevents/blob/master/events/api.py#L951
https://github.com/City-of-Helsinki/linkedevents/blob/master/events/api.py#L766

There are no tests for these parameters, though.

**Comment by Rikuoja** [comment]
Ah! Let's add tests then, so we remember the parameters exist :D

**Comment by Doatti** [comment]
Should we include translations of `DELETED` for Finnish and Swedish, or is it okay to simply replace names in each language with the same string?

**Comment by Rikuoja** [comment]
Yeah, let's add `POISTETTU` and `RADERAD`.

**Comment by aleksisalonen** [comment]
If it's going to be showing up on user applications, I think we should provide the info in three languages.

This info is meant for human eyes after all.

FI: Tapahtuma poistettu
SV: Evengemang raderad (?)
EN: Event deleted

**Comment by Rikuoja** [comment]
Well, it most likely is not shown in user applications, if the application coder knows what they are doing. It's mostly meant for the coder etc. to see that these items (with deleted=True) are no longer available, if they have specifically asked for those items to be listed.

**Comment by aleksisalonen** [comment]
True. But if we're going natural language anyway, why stop at DELETED instead of going Event deleted?

I'm fine with either one.

**Comment by Rikuoja** [comment]
Yeah, i'm just hoping the coder will visually notice this instantly. Tapahtuma poistettu looks like it doesn't stand out, even if the other fields are empty.

**Comment by aleksisalonen** [comment]
I suppose DELETED has the most shock value :)

**Comment by Doatti** [comment]
> Note that by default, the URI to the deleted event does not return this data. It returns HTTP 410 Gone as before.

Do you mean that the `show_deleted` parameter should also work for the detail view, and return the "stripped" version of the deleted event?

**Comment by Rikuoja** [comment]
I believe that would be the most consistent behavior? Without the parameter, behave as before.

**Comment by Rikuoja** [comment]
Hm, on the other hand, do we have *any* parameters that work both for detail and list? If not, perhaps this doesn't have to work either.

**Comment by Doatti** [comment]
For events, none of the filtering parameters work, because `get_object()` is overridden in the view set.

**Comment by Doatti** [comment]
Should we make similar "stripping" for deleted/deprecated keywords and places?

**Comment by Rikuoja** [comment]
Hm, I would say keywords and places may stay. In many cases, there might be old events referring to the old keywords and places, and it may be useful data to know what the actual old data was.
