### ISSUE TITLE
Do not list deleted events in inline event super and sub event listings

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents#390]
Currently, some weird interplay between `queryset=Event.objects.filter(deleted=False)` and django-mptt results in also deleted objects being listed in event `sub_events` field of the API.

So, these tests should pass, but don't. Add tests and investigate.

```
@pytest.mark.django_db
def test_get_event_list_sub_events(api_client, event, event2):
    event.super_event_type = Event.SuperEventType.RECURRING
    event.save()
    event2.super_event = event
    event2.save()

    # fetch event with sub event
    detail_url = reverse('event-detail', version='v1', kwargs={'pk': event.pk})
    response = get(api_client, detail_url)
    assert_event_fields_exist(response.data)
    assert response.data['sub_events']
    print(response.data['sub_events'])


@pytest.mark.django_db
def test_get_event_list_deleted_sub_events(api_client, event, event2):
    event.super_event_type = Event.SuperEventType.RECURRING
    event.save()
    event2.super_event = event
    event2.deleted = True
    event2.save()

    # fetch event with sub event deleted
    detail_url = reverse('event-detail', version='v1', kwargs={'pk': event.pk})
    response = get(api_client, detail_url)
    assert_event_fields_exist(response.data)
    assert not response.data['sub_events']
    print(response.data['sub_events'])

```

**Comment by Rikuoja** [comment]
This issue causes the UI to be unable to edit super events with deleted subevents. It also attempts to edit the deleted subevent as it is listed.

**Comment by Rikuoja** [comment]
Tried fixing this in the UI in https://github.com/City-of-Helsinki/linkedevents-ui/commit/2a3805ae2e600f90e630953cf3816fe703fca71d

**Comment by Doatti** [comment]
The first test passes but the second one doesn't, right?

**Comment by Doatti** [comment]
The reason for why it behaves like this is that the `queryset` argument on `HyperlinkedRelatedField` (from which `JSONLDRelatedField` inherits) is only used when *writing* to validate new relations.

Source: https://www.django-rest-framework.org/api-guide/relations/#hyperlinkedrelatedfield

**Comment by Rikuoja** [comment]
Ah! Well, then some custom code is apparently needed here.
