### ISSUE TITLE
Refine superevent creation in Lippupiste importer

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#393]
The Lippupiste importer creates a super event-sub event structure for all events, even if the event in question only has a single occurrence.

Refine the importer, so that when a single occurence event is detected, the superevent is not created and the event is imported as a single, normal event.

A slightly more complicated solution might take into consideration the possibility that a single occurence event might at a later time receive a second occurence, thus becoming an actual series that needs the super event-sub event structure.

**Comment by Doatti** [comment]
Should the importer delete super-events with a single child that are already in the database, or leave them be?

**Comment by Rikuoja** [comment]
Hm. Probably easier to leave existing superevents there, otherwise we will have to replace them with the subevent, and then if a second subevent appears later, undelete and unreplace them so that the old superevent is present once again? Or if that's easy, it's fine.

**Comment by Doatti** [comment]
Doesn't sound very easy :sweat_smile:. I'll try to find a way to leave them be.
