### ISSUE TITLE
Add tests for all use cases of `start` and `end` filters

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents#396]
The tests should verify that the `start` and `end` filters of the event endpoint only return the events taking place between the two timestamps, when provided with any of the four types of strings:

1) ISO date (no time) should refer to the start (if used in `start` filter) or end (if used in `end` filter) of the given day
2) complete ISO datetime
3) `today` should refer to the start (if used in `start` filter) or end (if used in `end` filter) of the current day
4) `now` should refer to the current exact datetime.

**Comment by Rikuoja** [comment]
Here, events with `has_end_time=False` are a special case.

They are short-lived events we have no exact end times for. Therefore, such events should not be returned if `start` parameter is later than their starting time.

**Comment by Rikuoja** [comment]
Cases 3 and 4 might require some mocking. We might not want tests that succeed or fail depending on what time of the day we run them, which time zone we are, whether we have moved to DST or not, and other time-dependent factors?

**Comment by Doatti** [comment]
I suggest we use [freezegun](https://github.com/spulec/freezegun) to mock the datetime module.

**Comment by Doatti** [comment]
We discussed with @Rikuoja about the case where `start` is after `end`. Currently the API allows this and can even return a non-empty list of events. We decided to change this behavior so that the API returns 400 and an error message, if `start` date time is after `end` date time.

**Comment by Doatti** [comment]
After further discussion, we decided not to do this change after all in fear of breaking some integration which relied on this "feature". :sweat_smile:
