### ISSUE TITLE
Add an is_free-parameter to event-endpoint

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#402]
Add a search parameter for the is_free-field to the event-endpoint.

Values can be "true" and "false" and results will vary accordingly.

**Comment by Doatti** [comment]
Just to make sure, an event "is free" if there is an Offer with `is_free=True` associated with it?

**Comment by Rikuoja** [comment]
Yeah. I guess we don't need to care about any other offers if there is one free in the mix, or is it possible that an event is free for some people and not for other people?

**Comment by Doatti** [comment]
I don't think so. The fields on the Offer model are `event, price, info_url, description, is_free` and none of those seem to associate an Offer with specific users.

**Comment by Doatti** [comment]
^ Misclick :sweat_smile:
