### ISSUE TITLE
Running migrations for django-heluser model throws an error.

### ISSUE THREAD

**Issue by zenbum** [City-of-Helsinki/linkedevents#56]
Trying to run `makemigrations` and `migrate` gives the following error:

> `django.db.utils.ProgrammingError: multiple default values specified for column "id" of table "helevents_user"`

**Comment by aapris** [comment]
Vote up. Until this is fixed developers can't clone the code and try Linked events locally.

**Comment by juyrjola** [comment]
Oh yeah, forgot to close this. It's fixed by b19feaf5.
